local events = require 'events'
local emitter = events:new()

emitter:on('h', function (...) 
    print('hello')
    print(...)
end)
emitter:once('h', function (...) 
    print('hello')
    print(...)
end)

emitter:once('hx', function (...) 
    print('helloxxxxxx')
    print(...)
end)
emitter:once('hx', function (...) 
    print('helloxxxxxx')
    print(...)
end)
emitter:once('hx', function (...) 
    print('helloxxxxxx')
    print(...)
end)
emitter:once('hx', function (...) 
    print('helloxxxxxx')
    print(...)
end)
emitter:on('hx', function (...) 
    print('helloxxxxxx')
    print(...)
end)

print(emitter:getMaxListeners())
print(emitter:setMaxListeners(15))
print(emitter:getMaxListeners())
print(emitter:listenerCount('h'))
print(emitter:listenerCount('hx'))


emitter:emit('h', { x = 3 }, 'yyoyoyo111')

emitter:emit('h', { x = 3 }, 'yyoyoyo2222')
emitter:emit('hx', { x = 1 }, 'yyoyoyo')
emitter:emit('hx', { x = 2 }, 'yyoyoyo')
emitter:emit('hx', { x = 3 }, 'yyoyoyo')